# Generated by Django 6.0.1 on 2026-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
